apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: csi-blob
spec:
  schema:
    apiVersion: v1alpha1
    kind: CSIBlob
    spec:
      name: string
      namespace: string | default=default
    status:
      deploymentConditions: ${repo.status.conditions}

  resources:
  - id: repo
    template:
      apiVersion: source.toolkit.fluxcd.io/v1
      kind: HelmRepository
      metadata:
        name: ${schema.spec.name}
        namespace: ${schema.spec.namespace}
      spec:
        interval: 1m0s
        url: https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts

  # - id: chart
  #   template:
  #     apiVersion: source.toolkit.fluxcd.io/v1
  #     kind: HelmChart
  #     metadata:
  #       name: ${schema.spec.name}
  #       namespace: ${schema.spec.namespace}
  #     spec:
  #       chart: blob-csi-driver
  #       version: '1.25.1'
  #       sourceRef:
  #         kind: HelmRepository
  #         name: ${schema.spec.name}
  #       interval: 1m
  #       ignoreMissingValuesFiles: true

  - id: release
    template:
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: ${schema.spec.name}
        namespace: ${schema.spec.namespace}
      spec:
        interval: 5m
        chart:
          spec:
            chart: blob-csi-driver
            version: '>=1.25.0'
            sourceRef:
              kind: HelmRepository
              name: ${schema.spec.name}
